/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Aadhar data parsed from XML */
export interface AadharData {
  /** Reference ID */
  referenceId: string
  /** Person's name */
  name: string
  /** Date of birth (DD-MM-YYYY) */
  dob: string
  /** Gender */
  gender: string
  /** Age in years (if DOB parsed successfully) */
  age?: number
  /** Commitment to Aadhar data */
  commitment: number
  /** XML digital signature verified */
  signatureVerified: boolean
}
/** DIDComm proof context for replay prevention */
export interface ProofContext {
  /** 32-byte nonce (hex string) */
  nonce: string
  /** 32-byte context hash (hex string) */
  contextHash: string
  /** 16-byte session ID (hex string) */
  sessionId: string
}
/** Proof metadata */
export interface ProofMetadata {
  /** Circuit identifier (e.g., "aadhaar-age-threshold-v1") */
  circuitId: string
  /** Verifying key hash (hex string) */
  vkHash: string
  /** Public outputs hash (hex string) */
  outputsHash: string
  /** Proof size in bytes */
  proofSizeBytes: number
  /** ZK scheme ("stark") */
  scheme: string
  /** Generation time in milliseconds */
  generationTimeMs?: number
}
/** Proof result with metadata */
export interface ProofResult {
  /** Proof bytes (base64 encoded) */
  proof: string
  /** Proof metadata */
  metadata: ProofMetadata
}
/** Complete DIDComm proof response */
export interface DidCommProofResponse {
  /** Program ID */
  programId: string
  /** Result ("pass" or "fail") */
  result: string
  /** Public inputs/outputs */
  public: PublicInputs
  /** Zero-knowledge proof */
  zk: ZKProof
}
export interface PublicInputs {
  nonce: string
  contextHash: string
  sessionId: string
  outputsHash: string
  vkHash: string
  commitment: number
}
export interface ZkProof {
  scheme: string
  circuitId: string
  vkHash: string
  proofB64: string
}
/**
 * Parse Aadhar XML data
 *
 * # Arguments
 * * `xmlContent` - Raw XML string from Aadhar file
 *
 * # Returns
 * Parsed Aadhar data with commitment
 *
 * # Example
 * ```javascript
 * const aadhar = parseAadharXml(xmlString);
 * console.log('Name:', aadhar.name);
 * console.log('Age:', aadhar.age);
 * console.log('Commitment:', aadhar.commitment);
 * ```
 */
export declare function parseAadharXml(xmlContent: string): AadharData
/**
 * Generate age threshold proof with DIDComm context binding
 *
 * # Arguments
 * * `xmlContent` - Raw XML string
 * * `minAge` - Minimum age threshold
 * * `context` - DIDComm proof context (nonce, context_hash, session_id)
 *
 * # Returns
 * Proof result with base64-encoded proof and metadata
 *
 * # Example
 * ```javascript
 * const proof = await proveAgeThreshold(xmlString, 18, {
 *   nonce: '0x' + randomBytes(32).toString('hex'),
 *   contextHash: '0x' + sha256(contextData).toString('hex'),
 *   sessionId: '0x' + randomBytes(16).toString('hex')
 * });
 * ```
 */
export declare function proveAgeThreshold(xmlContent: string, minAge: number, context: ProofContext): ProofResult
/**
 * Generate age range proof with DIDComm context binding
 *
 * # Arguments
 * * `xmlContent` - Raw XML string
 * * `minAge` - Minimum age
 * * `maxAge` - Maximum age
 * * `context` - DIDComm proof context
 *
 * # Example
 * ```javascript
 * const proof = await proveAgeRange(xmlString, 18, 65, context);
 * ```
 */
export declare function proveAgeRange(xmlContent: string, minAge: number, maxAge: number, context: ProofContext): ProofResult
/**
 * Create DIDComm proof response for age threshold proof
 *
 * # Arguments
 * * `proofResult` - Proof result from proveAgeThreshold
 * * `context` - Same context used for proof generation
 * * `minAge` - Same min age used for proof generation
 *
 * # Returns
 * Complete DIDComm PoE response ready to send
 *
 * # Example
 * ```javascript
 * const response = createDIDCommResponse(proofResult, context, 18);
 * await sendDIDCommMessage(response);
 * ```
 */
export declare function createDidcommAgeResponse(xmlContent: string, proofResult: ProofResult, context: ProofContext, minAge: number): DidCommProofResponse
/**
 * Verify age threshold proof with context
 *
 * # Arguments
 * * `proofBase64` - Base64-encoded proof
 * * `minAge` - Minimum age threshold
 * * `commitment` - Commitment value
 * * `context` - DIDComm context
 * * `outputsHash` - Expected outputs hash (hex string)
 *
 * # Returns
 * true if proof is valid, throws error otherwise
 */
export declare function verifyAgeThreshold(proofBase64: string, minAge: number, commitment: number, context: ProofContext, outputsHash: string): boolean
/** Get library version */
export declare function getVersion(): string
